=== aleksa-hubgit/xml-vebservisi/BACKEND/zig/src/main/resources/data/Zig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/zig" xmlns="http://www.ftn.uns.ac.rs/zig">
    <xs:element name="Prijava">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosilac_prijave" maxOccurs="1" minOccurs="1" type="TLice"> </xs:element>
                <xs:element name="Punomocnik" type="TLice"> </xs:element>
                <xs:element name="Zajednicki_predstavnik" type="TLice"> </xs:element>
                <xs:element name="Informacije_o_zigu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Tip_ziga" type="TTip_ziga"/>
                            <xs:element name="Tip_znaka" type="TTip_znaka"/>
                            <xs:element name="Izgled_znaka" type="xs:string"/>
                            <xs:element name="Boje_znaka">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="Boja"
                                            type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Transliteracija_znaka" type="xs:string"/>
                            <xs:element minOccurs="0" name="Prevod_znaka" type="xs:string"/>
                            <xs:element name="Opis_znaka" type="xs:string"/>
                            <xs:element name="Nicanska_klasifikacija">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="45" name="Klasa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:maxInclusive value="45"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Pravo_prvenstva" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Zatrazeno_pravo" type="xs:string"/>
                            <xs:element name="Osnov" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Takse">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Osnovna_taksa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Klasna_taksa">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Broj_klasa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                  <xs:maxInclusive value="45"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Iznos">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                  <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="0" name="Taksa_za_graficko_resenje">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Ukupna_taksa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Informacija_zavoda">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Broj_prijave" type="xs:string"/>
                            <xs:element name="Datum_podnosenja" type="xs:date"/>
                            <xs:element name="Prilozi" type="TPrilozi"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPrilozi">
        <xs:sequence>
            <xs:element name="Primerak_znaka" type="xs:string"/>
            <xs:element name="Spisak_robe_i_usluga" type="xs:string"/>
            <xs:element name="Punomocje" type="xs:string"/>
            <xs:element name="Naknadno_dostavljeno_punomocje" type="xs:boolean"/>
            <xs:element name="Generalno_punomocje" type="xs:string"/>
            <xs:element name="Opsti_akt" type="xs:string"/>
            <xs:element name="Dokaz_o_pravu_prvenstva" type="xs:string"/>
            <xs:element name="Dokaz_o_uplati_takse" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TTip_ziga">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INDIVIDUALNI"/>
            <xs:enumeration value="KOLEKTIVNI"/>
            <xs:enumeration value="GARANTNI"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TTip_znaka">
        <xs:restriction base="xs:string">
            <xs:enumeration value="VERBALNI"/>
            <xs:enumeration value="GRAFICKI"/>
            <xs:enumeration value="KOMBINOVANI"/>
            <xs:enumeration value="TRODIMENZIONALNI"/>
            <xs:enumeration value="DRUGA_VRSTA"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="adresa" type="TAdresa"/>
            <xs:element name="kontakt" type="TKontaktInformacije"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TKontaktInformacije">
        <xs:sequence>
            <xs:element name="broj_telefona" type="xs:string"/>
            <xs:element name="broj_faksa" type="xs:string"/>
            <xs:element name="e_posta" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravnoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="naziv" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizickoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="200"/>
                        <xs:minLength value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj" type="xs:string"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:fractionDigits value="0"/>
                        <xs:minInclusive value="10000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== aleksa-hubgit/xml-vebservisi/BACKEND/zig/src/main/resources/data/z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Prijava xmlns="http://www.ftn.uns.ac.rs/zig"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zig ../../../../../resources/xml_files/Zig.xsd">
    <Podnosilac_prijave xsi:type="TFizickoLice">
        <adresa>
            <ulica>Petra Kocica</ulica>
            <broj>38</broj>
            <postanski_broj>35000</postanski_broj>
            <mesto>Jagodina</mesto>
            <drzava>Srbija</drzava>
        </adresa>
        <kontakt>
            <broj_telefona>066222111</broj_telefona>
            <broj_faksa>15</broj_faksa>
            <e_posta>stefan.milosevic.e14@gmail.com</e_posta>
        </kontakt>
        <ime>Stefan</ime>
        <prezime>Milosevic</prezime>
    </Podnosilac_prijave>
    <Punomocnik xsi:type="TFizickoLice">
        <adresa>
            <ulica>Milana Mijalkovica</ulica>
            <broj>22</broj>
            <postanski_broj>35000</postanski_broj>
            <mesto>Jagodina</mesto>
            <drzava>Srbija</drzava>
        </adresa>
        <kontakt>
            <broj_telefona>066112222</broj_telefona>
            <broj_faksa>11</broj_faksa>
            <e_posta>nekaadresa@gmail.com</e_posta>
        </kontakt>
        <ime>Nenad</ime>
        <prezime>Miladinovic</prezime>
    </Punomocnik>
    <Zajednicki_predstavnik xsi:type="TFizickoLice">
        <adresa>
            <ulica>Zumze Zumzilica</ulica>
            <broj>11</broj>
            <postanski_broj>35000</postanski_broj>
            <mesto>Jagodina</mesto>
            <drzava>Srbija</drzava>
        </adresa>
        <kontakt>
            <broj_telefona>021021021</broj_telefona>
            <broj_faksa>021</broj_faksa>
            <e_posta>zumza@gmail.com</e_posta>
        </kontakt>
        <ime>Zumza</ime>
        <prezime>Stevanovic</prezime>
    </Zajednicki_predstavnik>
    <Informacije_o_zigu>
        <Tip_ziga>INDIVIDUALNI</Tip_ziga>
        <Tip_znaka>TRODIMENZIONALNI</Tip_znaka>
        <Izgled_znaka></Izgled_znaka>
        <Boje_znaka>
            <Boja>Crvena</Boja>
            <Boja>Plava</Boja>
        </Boje_znaka>
        <Opis_znaka></Opis_znaka>
        <Nicanska_klasifikacija>
            <Klasa>2</Klasa>
            <Klasa>5</Klasa>
            <Klasa>17</Klasa>
        </Nicanska_klasifikacija>
    </Informacije_o_zigu>
    <Takse>
        <Osnovna_taksa>222</Osnovna_taksa>
        <Ukupna_taksa>2222</Ukupna_taksa>
    </Takse>
    <Informacija_zavoda>
        <Broj_prijave></Broj_prijave>
        <Datum_podnosenja>2020-02-02</Datum_podnosenja>
        <Prilozi>
            <Primerak_znaka>true</Primerak_znaka>
            <Spisak_robe_i_usluga></Spisak_robe_i_usluga>
            <Punomocje></Punomocje>
            <Naknadno_dostavljeno_punomocje>false</Naknadno_dostavljeno_punomocje>
            <Generalno_punomocje>true</Generalno_punomocje>
            <Opsti_akt></Opsti_akt>
            <Dokaz_o_pravu_prvenstva></Dokaz_o_pravu_prvenstva>
            <Dokaz_o_uplati_takse></Dokaz_o_uplati_takse>
        </Prilozi>
    </Informacija_zavoda>
</Prijava>

=== aleksa-hubgit/xml-vebservisi/xmlvs/src/main/java/com/projekti/xmlvs/trademark/z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Prijava xmlns="http://www.ftn.uns.ac.rs/zig"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zig ../../../../../resources/xml_files/Zig.xsd">
    <Podnosilac_prijave xsi:type="TFizickoLice">
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj>35000</postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <broj_telefona></broj_telefona>
            <broj_faksa></broj_faksa>
            <e_posta></e_posta>
        </kontakt>
        <ime>Stefan</ime>
        <prezime>Milos</prezime>
    </Podnosilac_prijave>
    <Punomocnik xsi:type="TFizickoLice">
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj>35000</postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <broj_telefona></broj_telefona>
            <broj_faksa></broj_faksa>
            <e_posta></e_posta>
        </kontakt>
        <ime>Stefan</ime>
        <prezime>Milosevic</prezime>
    </Punomocnik>
    <Zajednicki_predstavnik xsi:type="TFizickoLice">
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj>35000</postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <broj_telefona></broj_telefona>
            <broj_faksa></broj_faksa>
            <e_posta></e_posta>
        </kontakt>
        <ime>Prsa</ime>
        <prezime>asgags</prezime>
    </Zajednicki_predstavnik>
    <Informacije_o_zigu>
        <Tip_ziga>INDIVIDUALNI_ZIG</Tip_ziga>
        <Tip_znaka>TRODIMENZIONALNI_ZNAK</Tip_znaka>
        <Izgled_znaka></Izgled_znaka>
        <Boje_znaka>
            <Boja></Boja>
        </Boje_znaka>
        <Opis_znaka></Opis_znaka>
        <Nicanska_klasifikacija>
            <Klasa>2</Klasa>
        </Nicanska_klasifikacija>
    </Informacije_o_zigu>
    <Takse>
        <Osnovna_taksa>222</Osnovna_taksa>
        <Ukupna_taksa>2222</Ukupna_taksa>
    </Takse>
    <Informacija_zavoda>
        <Broj_prijave></Broj_prijave>
        <Datum_podnosenja>2020-02-02</Datum_podnosenja>
        <Prilozi>
            <Primerak_znaka></Primerak_znaka>
            <Spisak_robe_i_usluga></Spisak_robe_i_usluga>
            <Punomocje></Punomocje>
            <Naknadno_dostavljeno_punomocje>false</Naknadno_dostavljeno_punomocje>
            <Generalno_punomocje></Generalno_punomocje>
            <Opsti_akt></Opsti_akt>
            <Dokaz_o_pravu_prvenstva></Dokaz_o_pravu_prvenstva>
            <Dokaz_o_uplati_takse></Dokaz_o_uplati_takse>
        </Prilozi>
    </Informacija_zavoda>
</Prijava>
