=== aleksa-hubgit/xml-vebservisi/BACKEND/xmlvs/data/a1_sema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/autorksa" xmlns="http://www.ftn.uns.ac.rs/autorksa">

    <xs:element name="autorksa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podnosilac_prijave" type="TPodnosilacPrijave"/>
                <xs:element minOccurs="0" name="pseudonim" type="xs:string"/>
                <xs:element name="punomocnik">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ime" type="xs:string"/>
                            <xs:element name="prezime" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podaci_o_naslovu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naslov" type="xs:string"/>
                            <xs:element name="alternativni_naslov" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podaci_o_preradi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naslov"/>
                            <xs:element name="autor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime" type="xs:string"/>
                                        <xs:element name="prezime" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vrsta_dela" type="xs:string"/>
                <xs:element name="podaci_o_autorima">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:element name="autor" type="TPodnosilacPrijave"/>
                                <xs:element name="autori">
                                    <xs:complexType>
                                        <xs:sequence maxOccurs="1">
                                            <xs:element maxOccurs="unbounded" name="autor">
                                                <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="ime" type="xs:string"/>
                                                  <xs:element name="prezime" type="xs:string"/>
                                                  <xs:element name="godina_smrti" type="xs:date"/>
                                                  </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="anonimno" type="xs:boolean"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="radnom_odnosu" type="xs:boolean"/>
                <xs:element name="namena_dela" type="xs:string"/>
                <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="ulica">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="200"/>
                        <xs:minLength value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj" type="xs:string"/>
            <xs:element name="postanski_broj">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:fractionDigits value="0"/>
                        <xs:minInclusive value="10000"/>
                        <xs:maxInclusive value="40000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="drzava" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TKontaktInformacije">
        <xs:sequence>
            <xs:element name="broj_telefona" type="xs:string"/>
            <xs:element name="e_posta" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element name="adresa" type="TAdresa"/>
            <xs:element name="kontakt" type="TKontaktInformacije"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravnoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="naziv" type="xs:string"/>
                    <xs:element name="sediste" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizickoLice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPodnosilacPrijave">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== aleksa-hubgit/xml-vebservisi/xmlvs/src/main/java/com/projekti/xmlvs/copyright/a1.xml
<?xml version="1.0" encoding="UTF-8"?>
<autorksa xmlns="http://www.ftn.uns.ac.rs/autorksa"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/autorksa a1_sema.xsd">
    <podnosilac_prijave>
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <postanski_broj>11000</postanski_broj>
            <mesto></mesto>
            <drzava></drzava>
        </adresa>
        <kontakt>
            <broj_telefona></broj_telefona>
            <e_posta></e_posta>
        </kontakt>
        <drzavljanstvo></drzavljanstvo>
    </podnosilac_prijave>
    <punomocnik>
        <ime></ime>
        <prezime></prezime>
    </punomocnik>
    <podaci_o_naslovu>
        <naslov></naslov>
        <alternativni_naslov></alternativni_naslov>
    </podaci_o_naslovu>
    <podaci_o_preradi>
        <naslov></naslov>
        <autor>
            <ime></ime>
            <prezime></prezime>
        </autor>
    </podaci_o_preradi>
    <vrsta_dela></vrsta_dela>
    <podaci_o_autorima>
        <autori>
            <autor>
                <ime></ime>
                <prezime></prezime>
                <godina_smrti>2020-01-01</godina_smrti>
            </autor>
        </autori>
    </podaci_o_autorima>
    <radnom_odnosu>false</radnom_odnosu>
    <namena_dela></namena_dela>
    <potpis></potpis>
</autorksa>
